

CREATE TABLE RADNIK (
    MBroj VARCHAR(13) primary key not null,
    Ime VARCHAR(20) not null,
    Presime varchar(30) not null,
    AdresaR varchar(30) not null 
);

CREATE TABLE FARMACEUT (
    MBrojF VARCHAR(13) primary key not null,
    StrucnaS VARCHAR(20) not null,
);

CREATE TABLE KOMERCIJALISTA (
    MbrojK VARCHAR(13) primary key not null,
    MobTel VARCHAR(20) not null
);

CREATE TABLE LEK (
    SifraL VARCHAR(20) primary key not null,
    NazivL VARCHAR(20),
    PrPotAU int not null
);

CREATE TABLE VELEDROGERIJA (
    SifraV VARCHAR(10) primary key not null,
    NazivV VARCHAR(20) not null,
    AdresaV VARCHAR(30) not null,
    TelefonV VARCHAR(20) not null
);



CREATE TABLE DOKUMENT (
    SifraD VARCHAR(10) primary key not null,
    DatumI DATE not null,
    UkupanI int not null,
    Rok int not null,
    NacinP varchar(20) not null,
    SifraV VARCHAR(10),
    MBrojK VARCHAR(13)
);


CREATE TABLE APOTEKA (
    SifraA VARCHAR(10) primary key not null,
    NazivA VARCHAR(20) not null,
    AdresaA VARCHAR(30) not null
);

CREATE TABLE RASPOLAZE (
    SifraA varchar(10) NOT NULL,
    SifraL VARCHAR(10) not null,
    RaspolazeK int not null,
    PrPotK int not null,
);

CREATE TABLE SADRZI (
    SifraD VARCHAR(10) not null,
    SifraL VARCHAR(10) not null,
    UkupnoIK int not null
);

CREATE TABLE ISPORUCENO (
    SifraD VARCHAR(10) not null,
    SifraL VARCHAR(10) not null,
    SifraA VARCHAR(10) not null,
    UkupnoIKA int not null
);

CREATE TABLE ZAMENA (
    SifraLO VARCHAR(10) not null,
    SifraLZ VARCHAR(10) not null,
);

CREATE TABLE ZAPOSLEN (
    MbrojF VARCHAR(13) not null,
    SifraA VARCHAR(10) not null,
    RanijeZU VARCHAR(20) not null,
    Datum date not null,
    Vreme time not null
);

-- Primary Keys

ALTER TABLE RASPOLAZE
ADD CONSTRAINT PK_RASPOLAZE primary key (SifraA, SifraL);

ALTER TABLE SADRZI 
ADD CONSTRAINT PK_SADRZI PRIMARY KEY (SifraD, SifraL);

ALTER TABLE ISPORUCENO
ADD CONSTRAINT PK_ISPORUCENO PRIMARY KEY (SifraD, SifraL, SifraA);

ALTER TABLE ZAMENA
ADD CONSTRAINT PK_ZAMENA PRIMARY KEY (SifraLO, SifraLZ);

ALTER TABLE ZAPOSLEN
ADD CONSTRAINT PK_ZAPOSLEN PRIMARY KEY (MbrojF, SifraA, RanijeZU);

-- Foreign Keys

ALTER TABLE FARMACEUT
ADD CONSTRAINT FK_FARMACEUT 
FOREIGN KEY (MBrojF) REFERENCES RADNIK(MBroj)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE KOMERCIJALISTA
ADD CONSTRAINT FK_KOMERCIJALISTA
FOREIGN KEY (MBrojK) REFERENCES RADNIK(MBroj)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE DOKUMENT
ADD CONSTRAINT FK_DOKUMENT
FOREIGN KEY (SifraV) REFERENCES VELEDROGERIJA(SifraV),
FOREIGN KEY (MBrojK) REFERENCES KOMERCIJALISTA(MBrojK)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE RASPOLAZE
ADD CONSTRAINT FK_RASPOLAZE
FOREIGN KEY (SifraA) REFERENCES APOTEKA(SifraA),
FOREIGN KEY (SifraL) REFERENCES LEK(SifraL)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE SADRZI
ADD CONSTRAINT FK_SADRZI
FOREIGN KEY (SifraD) REFERENCES DOKUMENT(SifraD),
FOREIGN KEY (SifraL) REFERENCES LEK(SifraL)
ON DELETE CASCADE
ON UPDATE CASCADE;


ALTER TABLE ISPORUCENO
ADD CONSTRAINT FK_ISPORUCENO
FOREIGN KEY (SifraD, SifraL) REFERENCES SADRZI(SifraD, SifraL),
FOREIGN KEY (SifraA) REFERENCES APOTEKA(SifraA)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE ZAMENA
ADD CONSTRAINT FK_ZAMENA
FOREIGN KEY (SifraLO) REFERENCES LEK(SifraL),
FOREIGN KEY (SifraLZ) REFERENCES LEK(SifraL)
ON DELETE CASCADE
ON UPDATE CASCADE;


ALTER TABLE ZAPOSLEN
ADD CONSTRAINT FK_ZAPOSLEN
FOREIGN KEY (MBrojF) REFERENCES FARMACEUT(MBrojF),
FOREIGN KEY (SifraA) REFERENCES APOTEKA(SifraA)
ON DELETE CASCADE
ON UPDATE CASCADE;






